<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tuit Fetcher</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="./index.css">
    <a href="/" style="position: absolute; right: 5%; top: -11%;">Go back</a>
  </head>
  <body>
    <h1>About Tuit
        <a href="http://bit.ly/julianmnst" class="about" target="_blank">
          <i class="fab fa-twitter"></i>
        </a>
    </h1>
    <div class="about-text">
        <p>
          This is an oversimplified Twitter client. It fetches the last 10 tweets from an account.
        </p>
        <p>
          This project is also aimed to improve my animation and CSS skills.
        </p>
        <p>
          Check the code in <a target="_blank" href="http://bit.ly/tuit-repo">Github</a>. I know it's a mess.
        </p>
        <p>
          Or check out <a target="_blank" href="http://bit.ly/julianmnst">my personal page</a>.
        </p>
    </div>
  </body>
</html>
