<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tuit Fetcher</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="./index.css">
  </head>
  <body>
    <h1>Tuit <i class="fab fa-twitter"></i></h1>

    <div class="container">
      <h5>Enter a valid twitter username to fetch it's latest tweets</h5>
      <input type="text" id="username" autocomplete="off">
      <button id="get-tweets">Get Tweets</button>
    </div>

    <div id="container" class="container"></div>
  </body>
  <script src="./index.js">
  </script>
</html>
